### ISSUE TITLE
Potential data corruption when uploading to gpu.

### ISSUE THREAD

**Issue by Shadowblitz16** [codingminecraft/MarioYoutube#4]
So I am on episode 24 and was having problems where extra blue lines would be drawn in random new places on startup.

I cloned this repo and added the linux versions of the libraries and set imgui to the default font and it seems that I reproduced it.
![image](https://user-images.githubusercontent.com/2453707/115978730-6d917b80-a536-11eb-8c86-75adc0f2f6b1.png)

it doesn't always happen so you have to keep rerunning it until you see lines but they are fairly common.

I am using opengl 30 and up stuff so I'm not sure if its a issue with that.

**Comment by athaun** [comment]
> So I am on episode 24 and was having problems where extra blue lines would be drawn in random new places on startup.
> 
> I cloned this repo and added the linux versions of the libraries and set imgui to the default font and it seems that I reproduced it.
> ![image](https://user-images.githubusercontent.com/2453707/115978730-6d917b80-a536-11eb-8c86-75adc0f2f6b1.png)
> 
> it doesn't always happen so you have to keep rerunning it until you see lines but they are fairly common.
> 
> I am using opengl 30 and up stuff so I'm not sure if its a issue with that.

I am not able to replicate the bug you are experiencing on manjaro linux :thinking:.
This is what I tested it on.
GPU: gtx 1660 super
Driver: proprietary nvidia 460.46
OpenGL version string: 4.6.0 NVIDIA 460.56
Manjaro linux

what graphics hardware and drivers are you using?
you can find out that info with these commands.
https://www.maketecheasier.com/graphics-card-information-linux/

My guess is that you have a driver problem that is causing it, although I do not know what the fix would be.

**Comment by Shadowblitz16** [comment]
I just today moved down to kubuntu 20.04 because it was lts
I ton of issues have gone away from apps not working or doing weird things, to my sound.

I can try to reproduce this tomorrow and see if the issue wasn't related to the os version.

I was using the official nvidia graphics drivers because a godot engine 4.0 build used vulkan and that wouldn't run for me because the open source drivers didn't support it.

**Comment by codingminecraft** [comment]
Hey ShadowBlits I'm closing this for now since it seems like the issue may have been resolved. You can reopen it if this is still an issue and give us some details about it and I'll take a look :)
